version: '3.8'
#docker run -p 8000:8000 -d --name unstructured-api -v ./unstructured-data:/data quay.io/unstructured-io/unstructured-api:latest --port 8000 --host 0.0.0.0
services:
  unstructured-api:
    image: quay.io/unstructured-io/unstructured-api:latest
    container_name: unstructured-api
    ports:
      - "8000:8000"
    command: ["--port", "8000", "--host", "0.0.0.0"]
    restart: unless-stopped
